ALTER TABLE "ErpSale"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "canceledById" INTEGER;

ALTER TABLE "ErpExpense"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "canceledById" INTEGER;

ALTER TABLE "ErpWaxTransaction"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "canceledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "canceledById" INTEGER;

CREATE INDEX IF NOT EXISTS "ErpSale_status_idx" ON "ErpSale"("status");
CREATE INDEX IF NOT EXISTS "ErpExpense_status_idx" ON "ErpExpense"("status");
CREATE INDEX IF NOT EXISTS "ErpWaxTransaction_status_idx" ON "ErpWaxTransaction"("status");
